In [1]:
import numpy as np

In [2]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

In [3]:
b = np.array([-1, -3, 9])

In [4]:
np.linalg.solve(A, b)

array([ 2.,  1., -2.])

In [5]:
np.linalg.inv(A)

array([[ 0.05263158,  0.10526316,  0.26315789],
       [-0.36842105,  0.26315789,  0.15789474],
       [-0.21052632,  0.57894737, -0.05263158]])

In [7]:
pip install sympy

     |████████████████████████████████| 6.2 MB 4.9 MB/s            
     |████████████████████████████████| 532 kB 20.4 MB/s            
Note: you may need to restart the kernel to use updated packages.


In [8]:
from sympy import *

augmented_A = Matrix([[2, -3, 1, -1],
                      [1, -1, 2, -3],
                      [3, 1, -1, 9]])

augmented_A.rref()[0]

Matrix([
[1, 0, 0,  2],
[0, 1, 0,  1],
[0, 0, 1, -2]])

In [9]:
augmented_A = Matrix([[1, -1, 4, -5],
                      [3, 0, 1, 0],
                      [-1, 1, -4, 20]])

augmented_A.rref()[0]

Matrix([
[1, 0,   1/3, 0],
[0, 1, -11/3, 0],
[0, 0,     0, 1]])

In [10]:
augmented_A = Matrix([[-1, 1, 2, 0],
                      [1, 2, 1, 6],
                      [-2, -1, 1, -6]])

augmented_A.rref()[0]

Matrix([
[1, 0, -1, 2],
[0, 1,  1, 2],
[0, 0,  0, 0]])

In [11]:
A = np.array([
    [2, 5, 2],
    [3, -2, 4],
    [-6, 1, -7]
])

b = np.array([-38, 17, -12])

In [12]:
np.linalg.solve(A, b)

array([ 3., -8., -2.])

In [13]:
A = np.array([
    [3, 0, -9],
    [7, -4, -1],
    [4, 6, 5]
])

b = np.array([33, -15, -6])

In [14]:
np.linalg.solve(A, b)

array([-1.,  3., -4.])

In [ ]:
 ,