In [1]:
import numpy as np

In [3]:
a = 7
B = [[1,2],
    [3, 4]]

np.dot(a, B)

array([[ 7, 14],
       [21, 28]])

In [4]:
A = [[1,2],
 [3,4]]
B = [[5,6],
 [7,8]]
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [5]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

In [9]:
# settlers example
#[wood, brick, sheep, wheat , ore]

resources = [[1, 1, 0, 0, 0],
    [1, 1, 1, 1, 0],
    [0, 0, 0, 2, 3],
    [0, 0, 1, 1, 1]]

resource_costs = [1, 2, 3, 5, 8]

total_costs = np.dot(resources, resource_costs)

In [10]:
total_costs

array([ 3, 11, 34, 16])

In [12]:
amounts = [6, 2, 1, 0]
resource_req = np.dot(amounts, resources)

In [13]:
resource_req

array([8, 8, 2, 4, 3])

In [ ]:
total_order_cost = np.dot(resourc)