In [3]:
from ps6_davidhackett12 import *
import numpy as np

In [4]:
## Test A and b to show results of forward elimination and solve completely
A = np.array([
     [1.0, 3.0, 1.0, 2.0],
     [2.0, 6.0, 4.0, 8.0],
     [0.0, 0.0, 2.0, 4.0]
])

b = np.array([1.0, 3.0, 1.0])

## Forward Elimination

Forward elimination works very similarly to the previous problem set. It does return A in row echelon form, as well as the pivots in a list with the index representing the row and the value representing the pivot column. It also returns rank and optionally will perform the same row operations on a vector b.

In [5]:
R, pivots, rank, _ = forward_elimination(A)
print(f"R: {R} \nPivots: {pivots} \nRank: {rank}")

R: [[1. 3. 1. 2.]
 [0. 0. 2. 4.]
 [0. 0. 0. 0.]] 
Pivots: [0, 2] 
Rank: 2


## Solve Completely

My solve completely function takes an A and b and returns a particular solution and a matrix representing the column space for N(A) with each column representing a vector in that space.

In [6]:
solve_completely(A, b)

(array([0.5, 0. , 0.5, 0. ]),
 array([[-3.,  0.],
        [ 1.,  0.],
        [ 0., -2.],
        [ 0.,  1.]]))

## Generate a Random Matrix

The generate random system function generates a random A and a random b that can be solved. It take in a value for the shape of the matrix as well as the columns that should have pivots.

In [7]:
A2, _ = generate_random_system((3,4), [0, 2])
print(A2)

[[-0.79718789 -0.03088469  0.66945157 -0.29083366]
 [ 0.37654068  0.01458796 -0.06601453  0.31717197]
 [-1.35036941 -0.05231608 -0.16709967 -1.4276818 ]]


Using forward elimination we can compare the expected pivots.

In [8]:
_, pivots, _, _ = forward_elimination(A2)
print(pivots)

[0, 2]


## Testing on a series of random matrices

Test solve completely will take an A and b and check whether solve completely worked as expected by plugging the particular solution x and X back into Ax = b and seeing if the b matches the input. It chooses a random column from X and multiplies it by a random coefficient.

In [9]:
try:
    test_solve_completely(A, b)
    print("success")
except AssertionError:
    print("failure")

success


Now test solve completely on random generates various shapes of matrices with different pivot columns and runs test solve completely on each of the randomly generated systems. It prints any linear system that produced an error and will print the number of tests passed and failed at the end.

In [10]:
test_solve_completely_on_random()

Tests Passed: 12 
 Tests Failed: 0
