In [1]:
from ps6_davidhackett12 import *
import numpy as np

## Forward Elimination

Forward elimination works very similarly to the previous problem set. It does return A in row echelon form, as well as the pivots in a list with the index representing the row and the value representing the pivot column. It also returns rank and optionally will perform the same row operations on a vector b. I created a test forward elimination function that utilzes an A with a known R, rank, and pivot columns.

In [2]:
test_forward_elimination()

Input A:
[[1. 3. 1. 2.]
 [2. 6. 4. 8.]
 [0. 0. 2. 4.]]

R expected:
[[1. 3. 1. 2.]
 [0. 0. 2. 4.]
 [0. 0. 0. 0.]]
vs R output
[[1. 3. 1. 2.]
 [0. 0. 2. 4.]
 [0. 0. 0. 0.]]

Expected Rank and Pivots:
 2, [0, 2]

Output Rank and Pivots:
 2, [0, 2]
Test successful


## Generate a random matrix

The generate random system function generates a random A and a random b that can either be solved or not solved. It take in a value for the shape of the matrix, the columns that should have pivots, and if the system should be solvable (its solvable by default)

In [3]:
A, b = generate_random_system((4,3), [0, 2], True)
print(A)

[[-0.2076522  -0.18622246  0.33994581]
 [ 2.69626534  2.41801031  2.27957262]
 [ 1.19054075  1.06767675 -0.75688965]
 [-0.30835322 -0.27653112  0.4011682 ]]


Some matrices always have solutions, for example a full rank square matrix. Generate random system will catch this with a custom exception

In [4]:
try:
    generate_random_system((2,2), [0,1], False)
except UnsolvableException as e:
    print(e)

shape (2, 2) with pivots [0, 1] will always be solvable


Also if you try to make a matrix with pivot cols that won't work, for example a matrix with the same pivot column for two rows

In [5]:
try:
    generate_random_system((2,2), [0,0], True)
except PivotException as e:
    print(e)

The pivots are out of order or duplicate columns


We can also see that the pivots are correct by using forward elimination

In [6]:
A, b = generate_random_system((3,3), [0, 2], True)
_, pivots, _, _ = forward_elimination(A)
print(pivots)

[0, 2]


## Solve a matrix completely

Takes in an A and b and returns xp, a particular solution, and xn the null space for the matrix. Each column of xn is a vector in the null space. If the null space is only 0 it will return the 0 vector as a matrix column, if A has no solutions it will return none for xp.

In [7]:
# At least one particular solution and Ax = 0 has a nontrivial solution
A, b = generate_random_system((3,4), [0, 1])
xp, xn = solve_completely(A, b)
print(f"xp: {xp}\n")
print(f"xn: {xn}")

xp: [2.19747454 1.91426231 0.         0.        ]

xn: [[-0.84388571 -1.01479363]
 [-0.82497964 -1.32017348]
 [ 1.          0.        ]
 [ 0.          1.        ]]


In [8]:
# No solution and Ax = 0 has a nontrivial solution
A, b = generate_random_system((3,4), [0, 2], False)
xp, xn = solve_completely(A, b)
print(f"xp: {xp}\n")
print(f"xn: {xn}")

xp: None

xn: [[-0.177561   -0.62731591]
 [ 1.          0.        ]
 [ 0.         -0.52692256]
 [ 0.          1.        ]]


In [9]:
# At least one particular solution and Ax = 0 only has the 0 vector as a solution
A, b = generate_random_system((3,4), [0, 1, 2])
xp, xn = solve_completely(A, b)
print(f"xp: {xp}\n")
print(f"xn: {xn}")

xp: [1.4910784  0.56959176 0.70200897 0.        ]

xn: [[0.]
 [0.]
 [0.]
 [0.]]


## Testing on a series of random matrices

Test solve completely will take an A and b and whether the system is solvable (default is true) and check whether solve completely worked as expected by plugging the particular solution x and X back into Ax = b and seeing if the b matches the input. It chooses a random column from X and multiplies it by a random coefficient. If not solvable it will check is xp = None

In [10]:
A, b = generate_random_system((3,4), [0, 1], True)
try:
    test_solve_completely(A, b, True)
    print("success")
except AssertionError:
    print("failure")

success


Now test solve completely on random generates various shapes of matrices with different pivot columns and runs test solve completely on each of the randomly generated systems (1 solvable and 1 not). It prints any linear system that produced an error and will print the number of tests passed and failed at the end.

In [11]:
test_solve_completely_on_random()

Tests Passed: 22 
Tests Failed: 0
