In [1]:
from ps6_davidhackett12 import *
import numpy as np

In [2]:
A1 = np.array([
     [1.0 ,3.0, 1.0],
     [3.0, 8.0, 2.0],
     [2.0, 4.0, 0.0]
])

A2 = np.array([
     [1.0, 3.0, 1.0, 2.0],
     [2.0, 6.0, 4.0, 8.0],
     [0.0, 0.0, 2.0, 4.0]
])

b2 = np.array([1.0, 3.0, 1.0])

A3 = np.array([
    [1, 2, 4],
    [1, 4, 8],
    [4, 8, 16]
])

In [3]:
forward_elimination(A1)

TypeError: object of type 'NoneType' has no len()

In [4]:
forward_elimination(A2, [])

(array([[1., 3., 1., 2.],
        [0., 0., 2., 4.],
        [0., 0., 0., 0.]]),
 [0, 2],
 [])

In [ ]:
forward_elimination(A3)

In [3]:
solve_completely(A2, b2)

NameError: name 'solve_completely' is not defined

In [3]:
test_solve_completely(A2,b2)

True

In [8]:
A4, b4 = generate_random_system((3,4), [1, 3])

In [9]:
forward_elimination(A4, b4)

(array([[-5.22432815e-01, -6.48132088e-01, -3.28704527e-01,
         -1.09565575e+00],
        [ 0.00000000e+00,  2.22044605e-16,  1.11022302e-16,
         -3.08597947e+00],
        [ 0.00000000e+00, -6.41841315e-18,  1.07813096e-16,
          0.00000000e+00]]),
 [0, 3],
 array([-1.24755078e+00, -1.01684739e+00, -1.11022302e-16]))

In [3]:
test_solve_completely(A4, b4)