In [1]:
import numpy as np
from ps2_davidhackett12 import eliminate, test_eliminate

(array([[ 1, -2],
       [ 0,  8]]), array([3., 1.]))


## 1 a)

In [2]:
"""
x - 2y = 1
3x + 2y = 11

Upper Triangular System should be:
[[1, -2]
[0, 8]]

solution should be [3, 1]
"""

A = np.array([[1, -2],
              [3, 2]])
b = np.array([1, 11])

print("eliminate on page 46:")
print(eliminate(A, b))

print("linalg.solve on page 46")
print(np.linalg.solve(A, b))

eliminate on page 46:
(array([[ 1, -2],
       [ 0,  8]]), array([3., 1.]))
linalg.solve on page 46
[3. 1.]


The two match the answer in the book

In [3]:
"""
2x + 4y - 2z = 2
4x + 9y - 3z = 8
-2x -3y + 7z = 10

Upper Triangular System should be:
[[2, 4, -2]
[0, 1, 1],
[0, 0, 4]]

solution should be [-1, 2, 2]
"""
A = np.array([[2, 4, -2],
              [4, 9, -3],
             [-2, -3, 7]])
b = np.array([2, 8, 10])

print("eliminate on page 50:")
print(eliminate(A, b))

print("linalg.solve on page 50")
print(np.linalg.solve(A, b))


eliminate on page 50:
(array([[ 2,  4, -2],
       [ 0,  1,  1],
       [ 0,  0,  4]]), array([-1.,  2.,  2.]))
linalg.solve on page 50
[-1.  2.  2.]


Once again they match!

## 1. b)

In [4]:
# Failing because a row change is needed

A = np.array([[0, 2],
             [3, -2]])

b = np.array([4, 5])


print("eliminate trying solve a system that requires a row change")
try:
    eliminate(A, b)
except OverflowError:
    print("Failed because of a row change")
    
print("Trying with linalg.solve")
print(np.linalg.solve(A,b))
    
    

eliminate trying solve a system that requires a row change
Failed because of a row change
Trying with linalg.solve
[-2.  2.]


/Users/davidhackett/school-projects/linear_algebra/homeworks/ps2_davidhackett12.py:26: RuntimeWarning: divide by zero encountered in long_scalars
  pivot = A[i + j][i]/A[i][i]
/Users/davidhackett/school-projects/linear_algebra/homeworks/ps2_davidhackett12.py:27: RuntimeWarning: invalid value encountered in multiply
  A[i + j] = A[i + j] - (A[i] * pivot)


Apparently in the case where a row change is needed it throws an overflow error because it interprets 3/0 as inf. Later it fails when trying to use that to multiply the top equation. Obviously it works with linalg.solve

In [5]:
# Trying a case with no solutions

A = np.array([[2, 4],
            [1, 2]])

b = np.array([-1, 2])

print("Trying eliminate with system that has no solutions")
print(eliminate(A, b))

Trying eliminate with system that has no solutions
(array([[2, 4],
       [0, 0]]), array([-inf,  inf]))


/Users/davidhackett/school-projects/linear_algebra/homeworks/ps2_davidhackett12.py:37: RuntimeWarning: divide by zero encountered in long_scalars
  x[i] = answer / A[i][i]


Interestingly there isn't an error here, but having -inf and inf as a solution is obviously wrong. It somewhat successfully creates the upper triangular system (though its not really a triange), but fails when trying to do back substituion since the last equation is all 0s dividing by 0 again and making the answer -inf, inf.

In [6]:
# Trying a case with infinite solutions

A = np.array([[2, 4],
            [1, 2]])

b = np.array([6, 3])

print("Trying eliminate with system that has infinite solutions")
print(eliminate(A, b))

Trying eliminate with system that has infinite solutions
(array([[2, 4],
       [0, 0]]), array([nan, nan]))


/Users/davidhackett/school-projects/linear_algebra/homeworks/ps2_davidhackett12.py:37: RuntimeWarning: invalid value encountered in long_scalars
  x[i] = answer / A[i][i]


This also runs, but again the solution (nan, nan) is obviously wrong. It fails at the same point as the last one, but instead of trying to divide a non 0 number by 0 it attempts 0/0 giving us (nan, nan) as the result.

## 1 C

In [7]:
tests = [100, 200, 400, 800, 1600]
results = []

for test in tests:
    results.append(test_eliminate(test))

In [8]:
for i, result in enumerate(results):
    print(f"\nSolving Rx = w with n = 100 ·2^{i} using eliminate takes approximately {result[0]} milliseconds. Using linalg.solve, it takes approximately {result[1]} milliseconds.")



Solving Rx = w with n = 100 ·2^0 using eliminate takes approximately 0.018851304054260255 milliseconds. Using linalg.solve, it takes approximately 0.0028564929962158203 milliseconds.

Solving Rx = w with n = 100 ·2^1 using eliminate takes approximately 0.08215148448944092 milliseconds. Using linalg.solve, it takes approximately 0.0030572891235351564 milliseconds.

Solving Rx = w with n = 100 ·2^2 using eliminate takes approximately 0.362457275390625 milliseconds. Using linalg.solve, it takes approximately 0.00292820930480957 milliseconds.

Solving Rx = w with n = 100 ·2^3 using eliminate takes approximately 1.924580717086792 milliseconds. Using linalg.solve, it takes approximately 0.01480712890625 milliseconds.

Solving Rx = w with n = 100 ·2^4 using eliminate takes approximately 9.352365279197693 milliseconds. Using linalg.solve, it takes approximately 0.06510248184204101 milliseconds.


Obviously based on these results solve is much faster and the gap widens as n increases. 