In [6]:
import numpy as np

In [7]:
v = np.random.randn(3)

In [8]:
print(v)

[-0.58879929 -0.1175572   0.3368309 ]


In [9]:
u = v / np.sqrt(np.dot(v, v))

In [10]:
print(u)

[-0.85525718 -0.17075707  0.48926188]


In [11]:
# Just to test, should equal 1
np.dot(u, u)

1.0

In [12]:
W = np.random.randn(30, 3)

In [13]:
print(W)

[[ 0.307936    1.12868485  0.24930849]
 [-1.4077039   0.81512806  0.24050199]
 [-0.39417166 -0.9912869  -0.51885432]
 [ 1.2552625   1.23842005 -1.6802248 ]
 [-1.52196388  1.46554312  1.30977432]
 [ 0.55600382  0.06528487 -0.23888326]
 [ 0.43464298 -0.44949943  0.70807669]
 [-0.88112651  0.72863933 -0.04561416]
 [-0.41668925 -2.35139779 -0.21538567]
 [-0.45615827  1.00222432 -0.85153793]
 [-1.32061357 -0.50057071 -1.31060877]
 [-1.75363375  1.29340808  1.23857495]
 [ 0.72372769  0.04728526 -0.03791235]
 [-2.42680336 -1.33464018 -0.01752383]
 [ 0.15133708 -1.10421438  0.48541477]
 [-0.20468713 -0.47642881  1.37401456]
 [ 0.33778362  0.05676501 -1.22964181]
 [-0.53549708 -1.67915293  1.18276863]
 [-0.27085835 -0.49284999 -1.32063018]
 [-1.65308079 -0.3939893   0.90862172]
 [-0.41754893 -1.47461717  0.01397116]
 [-0.35168591 -1.33942022 -0.53130087]
 [-0.94869839  0.34300725 -0.38954961]
 [-0.93381756 -1.1432847  -0.38012748]
 [ 2.14690186 -0.02180964  0.65448861]
 [-0.6173042  -0.12821264

In [17]:
# Is there a better way to do this?
dot_products = []

for w in W:
    dot_products.append(np.abs(np.dot(u,w)))
    
print(np.mean(dot_products))

0.9320633647200778
